name: Importador Automático de Issues

on:
  workflow_dispatch: # Permite rodar manualmente clicando no botão "Run workflow"
  push:
    branches:
      - main # Monitora a branch correta
    paths:
      - 'snake-duel-issues.csv'

# Define as permissões necessárias para o token nativo do GitHub rodar a automação
permissions:
  contents: write
  issues: write

jobs:
  import-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Importar Issues do CSV
        uses: jasonm23/action-issue-importer@v1
        with:
          # Usando o token automático gerado pelo próprio GitHub Actions
          github-token: ${{ secrets.GITHUB_TOKEN }}
          csv-filepath: 'snake-duel-issues.csv'
