name: Importador Automático de Issues

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'snake-duel-issues.csv'

permissions:
  contents: read
  issues: write

jobs:
  import-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Importar Issues do CSV
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tail -n +2 snake-duel-issues.csv | while IFS=',' read -r title body
          do
            echo "Criando issue: $title"

            gh issue create \
              --title "$title" \
              --body "$body"
          done
